/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSatZYXRouteImport } from './routes/api/sat/$z/$y/$x'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSatZYXRoute = ApiSatZYXRouteImport.update({
  id: '/api/sat/$z/$y/$x',
  path: '/api/sat/$z/$y/$x',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sat/$z/$y/$x': typeof ApiSatZYXRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sat/$z/$y/$x': typeof ApiSatZYXRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sat/$z/$y/$x': typeof ApiSatZYXRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/sat/$z/$y/$x'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/sat/$z/$y/$x'
  id: '__root__' | '/' | '/api/sat/$z/$y/$x'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSatZYXRoute: typeof ApiSatZYXRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sat/$z/$y/$x': {
      id: '/api/sat/$z/$y/$x'
      path: '/api/sat/$z/$y/$x'
      fullPath: '/api/sat/$z/$y/$x'
      preLoaderRoute: typeof ApiSatZYXRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSatZYXRoute: ApiSatZYXRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
